services:
  - type: web
    name: bmi-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrc  # 替换为你的数据库名称
          property: connectionString
